theme: minima

siteConfig:
  title: Mizo
  url: https://mizo.cadoangelus.me
  author: Sherin Binu
  email: sherinbinu@hotmail.com
  description: My Daily Blog of learning Mizo

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    twitter: sherondale13
    github: sherondale
    rss: false

plugins:
  - resolve: saber-plugin-query-posts